- hosts: 127.0.0.1
  gather_facts: no
  vars:
   scopes:
      - https://www.googleapis.com/auth/compute
  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: "{{ disk_name }}"
        size_gb: 60
        source_image: "{{ image }}"
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk
