- hosts: ec2-18-206-85-101.compute-1.amazonaws.com
  tasks:
      - name: print hello
        shell: echo "hello world" 
        register: helo

      - name: Print helo
        debug:
          msg: "helo output: {{ helo.stdout }}"
